const tagsData = [
  "Murder",
  "Child Abuse",
  "Assassination",
  "Robbery",
  "Fraud",
  "Kidnapping",
  "Domestic Violence",
  "Cybercrime",
  "Drug Trafficking",
  "Money Laundering",
  "Terrorism",
  "Human Trafficking",
  "Sexual Assault",
  "Arson",
  "Identity Theft",
  "Embezzlement",
  "Extortion",
  "Forgery",
  "Burglary",
  "Assault",
  "Hate Crime",
  "Stalking",
  "Bribery",
  "Espionage",
  "Insider Trading",
  "Counterfeiting",
  "Blackmail",
  "Racketeering",
  "Vandalism",
  "Perjury",
  "Tax Evasion",
  "Arms Trafficking",
  "Smuggling",
  "Genocide",
  "War Crimes",
  "Piracy",
  "Organized Crime",
  "Hacking",
  "Conspiracy",
  "Manslaughter",
  "Vehicular Homicide",
  "Animal Cruelty",
  "Environmental Crime",
  "Intellectual Property Theft",
  "Carjacking",
  "Trespassing",
  "Juvenile Delinquency",
  "Public Corruption",
  "White Collar Crime",
];

export default tagsData;
